language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - 'composer install --dev --prefer-source'

script: vendor/bin/codecept run --no-colors --coverage-xml

after_script:
  - if [ $(phpenv version-name) = "7.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ $(phpenv version-name) = "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi
